-- Tabla y políticas para comentarios públicos de productos.
-- Ejecuta este script en el SQL editor de Supabase antes de usar la sección
-- de comentarios en la ficha de producto.

create table if not exists public.product_comments (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  author_name text not null,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists product_comments_product_id_created_at_idx
  on public.product_comments (product_id, created_at desc);

alter table public.product_comments enable row level security;

drop policy if exists "Cualquiera puede leer comentarios" on public.product_comments;
create policy "Cualquiera puede leer comentarios"
  on public.product_comments
  for select
  using (true);

drop policy if exists "Usuarios autenticados pueden comentar" on public.product_comments;
create policy "Usuarios autenticados pueden comentar"
  on public.product_comments
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.products
      where products.id = product_comments.product_id
        and products.is_visible = true
        and products.status in ('available', 'reserved')
    )
  );

drop policy if exists "Solo admins pueden eliminar comentarios" on public.product_comments;
create policy "Solo admins pueden eliminar comentarios"
  on public.product_comments
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );
