export const gameSystems = [
  {
    id: "all",
    name: "Todos",
    slug: "all",
  },
  {
    id: "40k",
    name: "Warhammer 40K",
    slug: "40k",
  },
  {
    id: "aos",
    name: "Age of Sigmar",
    slug: "aos",
  },
  {
    id: "fantasy",
    name: "Warhammer Fantasy",
    slug: "fantasy",
  },
  {
    id: "otros",
    name: "Otros",
    slug: "otros",
  },
];

export const factions = [
  {
    id: "all",
    gameSystemId: "all",
    name: "Todas",
    slug: "all",
  },
  {
    id: "blood-angels",
    gameSystemId: "40k",
    name: "Blood Angels",
    slug: "blood-angels",
  },
  {
    id: "eldars",
    gameSystemId: "40k",
    name: "Eldars",
    slug: "eldars",
  },
  {
    id: "orkos",
    gameSystemId: "40k",
    name: "Orkos",
    slug: "orkos",
  },
  {
    id: "necrones",
    gameSystemId: "40k",
    name: "Necrones",
    slug: "necrones",
  },
  {
    id: "stormcast-eternals",
    gameSystemId: "aos",
    name: "Stormcast Eternals",
    slug: "stormcast-eternals",
  },
  {
    id: "skaven",
    gameSystemId: "aos",
    name: "Skaven",
    slug: "skaven",
  },
  {
    id: "altos-elfos",
    gameSystemId: "fantasy",
    name: "Altos Elfos",
    slug: "altos-elfos",
  },
  {
    id: "condes-vampiro",
    gameSystemId: "fantasy",
    name: "Condes Vampiro",
    slug: "condes-vampiro",
  },
  {
    id: "otros",
    gameSystemId: "otros",
    name: "Otros",
    slug: "otros",
  },
];

export const products = [
  {
    id: 1,
    name: "Bibliotecario Blood Angels de metal",
    system: "Warhammer 40K",
    systemSlug: "40k",
    faction: "Blood Angels",
    factionSlug: "blood-angels",
    condition: "Metal · Pintado",
    price: 18,
    status: "Disponible",
  },
  {
    id: 2,
    name: "Pack Eldars clásicos",
    system: "Warhammer 40K",
    systemSlug: "40k",
    faction: "Eldars",
    factionSlug: "eldars",
    condition: "Plástico · Montado",
    price: 42,
    status: "Reservado",
  },
  {
    id: 3,
    name: "Orkos antiguos lote x10",
    system: "Warhammer 40K",
    systemSlug: "40k",
    faction: "Orkos",
    factionSlug: "orkos",
    condition: "Plástico · Sin pintar",
    price: 35,
    status: "Disponible",
  },
  {
    id: 4,
    name: "Necrones clásicos lote inicial",
    system: "Warhammer 40K",
    systemSlug: "40k",
    faction: "Necrones",
    factionSlug: "necrones",
    condition: "Plástico · Imprimado",
    price: 28,
    status: "Disponible",
  },
  {
    id: 5,
    name: "Stormcast Eternals pack héroes",
    system: "Age of Sigmar",
    systemSlug: "aos",
    faction: "Stormcast Eternals",
    factionSlug: "stormcast-eternals",
    condition: "Plástico · Montado",
    price: 30,
    status: "Disponible",
  },
  {
    id: 6,
    name: "Skaven antiguos lote ratas de clan",
    system: "Age of Sigmar",
    systemSlug: "aos",
    faction: "Skaven",
    factionSlug: "skaven",
    condition: "Plástico · Sin pintar",
    price: 25,
    status: "Reservado",
  },
  {
    id: 7,
    name: "Altos Elfos lanceros clásicos",
    system: "Warhammer Fantasy",
    systemSlug: "fantasy",
    faction: "Altos Elfos",
    factionSlug: "altos-elfos",
    condition: "Plástico · Pintado",
    price: 32,
    status: "Disponible",
  },
  {
    id: 8,
    name: "Condes Vampiro esqueletos antiguos",
    system: "Warhammer Fantasy",
    systemSlug: "fantasy",
    faction: "Condes Vampiro",
    factionSlug: "condes-vampiro",
    condition: "Plástico · Montado",
    price: 22,
    status: "Disponible",
  },
];